<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html><html lang="ko"><head><jsp:include page="/WEB-INF/jsp/common/head.jsp"><jsp:param name="dsTitle" value="DevSync Admin - 사용자 작업 이력"/></jsp:include></head><body class="ds-body min-h-screen flex"><jsp:include page="/WEB-INF/jsp/common/sidebar.jsp"/><div class="flex-grow flex flex-col min-h-screen"><jsp:include page="/WEB-INF/jsp/common/header.jsp"><jsp:param name="dsPageTitle" value="사용자 작업 이력"/></jsp:include><main class="ds-page"><div class="ds-page-head"><div><h1 class="ds-page-title">사용자 작업 이력</h1><p class="ds-page-desc">일반사용자 사이트의 등록·수정·삭제 작업만 조회합니다. 단순 조회는 기록하지 않습니다.</p></div></div>
<form class="ds-card ds-card-inner ds-mb-20" method="get"><div class="ds-form-12">
<div class="ds-field ds-col-2"><label>회사ID</label><input class="ds-input" name="coId" value="${search.coId}"></div>
<div class="ds-field ds-col-2"><label>사용자ID</label><input class="ds-input" name="userId" value="${search.userId}"></div>
<div class="ds-field ds-col-2"><label>작업</label><select class="ds-select" name="actionSeCd"><option value="">전체</option><option value="REG" ${search.actionSeCd eq 'REG'?'selected':''}>등록</option><option value="MDFCN" ${search.actionSeCd eq 'MDFCN'?'selected':''}>수정</option><option value="DEL" ${search.actionSeCd eq 'DEL'?'selected':''}>삭제</option></select></div>
<div class="ds-field ds-col-2"><label>시작일</label><input type="date" class="ds-input" name="sDate" value="${search.sDate}"></div>
<div class="ds-field ds-col-2"><label>종료일</label><input type="date" class="ds-input" name="eDate" value="${search.eDate}"></div>
<div class="ds-field ds-col-2"><label>접속IP</label><input class="ds-input" name="clientIpAddr" value="${search.clientIpAddr}"></div>
<div class="ds-field ds-col-11"><label>메뉴/대상/URL 검색</label><input class="ds-input" name="searchValue" value="${search.searchValue}" placeholder="사용자명/메뉴/대상/URL"></div><div class="ds-field ds-col-1 flex items-end"><button class="ds-btn ds-btn-primary w-full">조회</button></div></div></form>
<section class="ds-card ds-card-inner"><div class="ds-table-wrap"><table class="ds-table"><thead><tr><th>일시</th><th>회사</th><th>사용자</th><th>작업</th><th>메뉴</th><th>대상</th><th>IP</th><th>요청 URL</th></tr></thead><tbody><c:forEach items="${list}" var="r"><tr><td>${r.REG_DT}</td><td>${r.CO_NM}<br><span class="text-xs text-gray-500">${r.CO_ID}</span></td><td>${r.USER_NM}<br><span class="text-xs text-gray-500">${r.USER_ID}</span></td><td>${r.ACTION_SE_CD}</td><td>${r.MENU_NM}</td><td>${r.TARGET_ID}</td><td>${r.CLIENT_IP_ADDR}</td><td class="text-xs">${r.REQUEST_URI}</td></tr></c:forEach><c:if test="${empty list}"><tr><td colspan="8" class="ds-empty">작업 이력이 없습니다.</td></tr></c:if></tbody></table></div></section></main></div></body></html>
