CREATE TABLE IF NOT EXISTS `schdl_info` (
    `SCHDL_SN` BIGINT NOT NULL AUTO_INCREMENT COMMENT '일정일련번호',
    `CO_ID` VARCHAR(20) NOT NULL COMMENT '회사ID',
    `SCHDL_SE_CD` VARCHAR(30) NOT NULL COMMENT '일정구분코드',
    `SCHDL_NM` VARCHAR(100) NOT NULL COMMENT '일정명',
    `BGNG_DT` DATETIME NOT NULL COMMENT '시작일시',
    `END_DT` DATETIME NOT NULL COMMENT '종료일시',
    `ALL_DAY_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '종일여부',
    `PLACE_NM` VARCHAR(100) DEFAULT NULL COMMENT '장소명',
    `SCHDL_CN` VARCHAR(1000) DEFAULT NULL COMMENT '일정내용',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    `REG_DT` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    `MDFCN_DT` DATETIME DEFAULT NULL COMMENT '수정일시',
    `RGTR_ID` VARCHAR(50) DEFAULT NULL COMMENT '등록자아이디',
    `MDFR_ID` VARCHAR(50) DEFAULT NULL COMMENT '수정자아이디',
    PRIMARY KEY (`SCHDL_SN`),
    KEY `IDX_SCHDL_INFO_CO_DT` (`CO_ID`, `BGNG_DT`, `END_DT`),
    KEY `IDX_SCHDL_INFO_SE` (`SCHDL_SE_CD`),
    CONSTRAINT `FK_SCHDL_INFO_CO` FOREIGN KEY (`CO_ID`) REFERENCES `co_info` (`CO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='일정정보';

CREATE TABLE IF NOT EXISTS `schdl_user_rel` (
    `SCHDL_SN` BIGINT NOT NULL COMMENT '일정일련번호',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '사용자아이디',
    `REG_DT` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (`SCHDL_SN`, `USER_ID`),
    KEY `IDX_SCHDL_USER_REL_USER` (`USER_ID`),
    CONSTRAINT `FK_SCHDL_USER_REL_SCHDL` FOREIGN KEY (`SCHDL_SN`) REFERENCES `schdl_info` (`SCHDL_SN`) ON DELETE CASCADE,
    CONSTRAINT `FK_SCHDL_USER_REL_USER` FOREIGN KEY (`USER_ID`) REFERENCES `user_info` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='일정사용자관계';

INSERT INTO cmn_cd_group (CD_GROUP_ID, CD_GROUP_NM, USE_YN, SORT_SEQ, RMRK_CN, REG_DT)
SELECT 'CAL_SCHDL_SE_CD', '종합일정구분코드', 'Y', 120, '휴가, 출장, 외근, 회의, 프로젝트 등 종합 일정 구분', NOW()
WHERE NOT EXISTS (SELECT 1 FROM cmn_cd_group WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD');

INSERT INTO cmn_cd (CD_GROUP_ID, CD, CD_NM, CD_EXPLN, SORT_SEQ, DFLT_YN, USE_YN, REG_DT)
SELECT 'CAL_SCHDL_SE_CD', 'VAC', '휴가', '휴가 일정', 10, 'Y', 'Y', NOW()
WHERE NOT EXISTS (SELECT 1 FROM cmn_cd WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD' AND CD = 'VAC');
INSERT INTO cmn_cd (CD_GROUP_ID, CD, CD_NM, CD_EXPLN, SORT_SEQ, DFLT_YN, USE_YN, REG_DT)
SELECT 'CAL_SCHDL_SE_CD', 'BIZTRIP', '출장', '출장 일정', 20, 'N', 'Y', NOW()
WHERE NOT EXISTS (SELECT 1 FROM cmn_cd WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD' AND CD = 'BIZTRIP');
INSERT INTO cmn_cd (CD_GROUP_ID, CD, CD_NM, CD_EXPLN, SORT_SEQ, DFLT_YN, USE_YN, REG_DT)
SELECT 'CAL_SCHDL_SE_CD', 'OUTSIDE', '외근', '외근 일정', 30, 'N', 'Y', NOW()
WHERE NOT EXISTS (SELECT 1 FROM cmn_cd WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD' AND CD = 'OUTSIDE');
INSERT INTO cmn_cd (CD_GROUP_ID, CD, CD_NM, CD_EXPLN, SORT_SEQ, DFLT_YN, USE_YN, REG_DT)
SELECT 'CAL_SCHDL_SE_CD', 'HOME', '재택', '재택 일정', 40, 'N', 'Y', NOW()
WHERE NOT EXISTS (SELECT 1 FROM cmn_cd WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD' AND CD = 'HOME');
INSERT INTO cmn_cd (CD_GROUP_ID, CD, CD_NM, CD_EXPLN, SORT_SEQ, DFLT_YN, USE_YN, REG_DT)
SELECT 'CAL_SCHDL_SE_CD', 'MEETING', '회의', '회의 일정', 50, 'N', 'Y', NOW()
WHERE NOT EXISTS (SELECT 1 FROM cmn_cd WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD' AND CD = 'MEETING');
INSERT INTO cmn_cd (CD_GROUP_ID, CD, CD_NM, CD_EXPLN, SORT_SEQ, DFLT_YN, USE_YN, REG_DT)
SELECT 'CAL_SCHDL_SE_CD', 'PROJECT', '프로젝트', '프로젝트 일정', 60, 'N', 'Y', NOW()
WHERE NOT EXISTS (SELECT 1 FROM cmn_cd WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD' AND CD = 'PROJECT');
INSERT INTO cmn_cd (CD_GROUP_ID, CD, CD_NM, CD_EXPLN, SORT_SEQ, DFLT_YN, USE_YN, REG_DT)
SELECT 'CAL_SCHDL_SE_CD', 'ETC', '기타', '기타 일정', 90, 'N', 'Y', NOW()
WHERE NOT EXISTS (SELECT 1 FROM cmn_cd WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD' AND CD = 'ETC');

-- 2026-07-14 회의 반영: 캘린더 직접 등록 대상에서 프로젝트/재택 제외
UPDATE cmn_cd SET USE_YN = 'N'
 WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD'
   AND CD IN ('PROJECT','HOME','REMOTE','BTRP','MEET');
UPDATE cmn_cd SET USE_YN = 'Y'
 WHERE CD_GROUP_ID = 'CAL_SCHDL_SE_CD'
   AND CD IN ('VAC','BIZTRIP','OUTSIDE','MEETING','ETC');
